### PR TITLE
Create mcs_example.json

### PR DESCRIPTION
**Pull request by amessina71**
An example of Microsoft's ASR output

### CODE REVIEW

**Comment by amessina71** [comment]
Added an example of transcript from Microsoft Cognitive Services

**Comment by tmandersbeeldengeluid** [comment]
I don't have push/pull request rights, so I decided to attach Kaldi output directly here (2 examples: JSON & CTM as txt files, regards, Tim 
[KladiTranscriptNISV.txt](https://github.com/ebu/ai-benchmarking-stt/files/2759708/KladiTranscriptNISV.txt)
[KladiTranscriptNISV_CTM.txt](https://github.com/ebu/ai-benchmarking-stt/files/2759713/KladiTranscriptNISV_CTM.txt)

**Comment by pietrop** [comment]
Thanks @amessina71 , do you know if Microsoft also offer word level timings?

**Comment by amessina71** [comment]
> Thanks @amessina71 , do you know if Microsoft also offer word level timings?

checking this out. In the meantime: the time unit of transcript chunks from Microsoft is 100 nanoseconds (weird enough). So, 1200000 corresponds to (1200000 units * 100ns/unit ) / 10^9 ns /s = 0.12 s

**Comment by amessina71** [comment]
> Thanks @amessina71 , do you know if Microsoft also offer word level timings?

I checked this. It seems they do not provide such a feature. As far as we know, they provide only paragraph-level timings.

**Pull request merged**
